---
- name: Updating the repo and cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Download and Install Grafana Package on Debian
  apt:
    deb: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_{{ grafana_version }}_amd64.deb 

- name: Move the configuration File of Grafana
  copy:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini

- name: Create grafana Dashboard directory
  file:
    path: /var/lib/grafana/dashboards
    state: directory
    owner: grafana
    group: grafana
    mode: 0755

- name: Add Dashboard to grafana
  copy:
    src: "{{ item }}"
    dest: /var/lib/grafana/dashboards/
    owner: grafana
    group: grafana
  with_items:
    - mongodb.json
    - mysql.json
    - node-exporter.json
    - prometheus-redis.json
    - apache.json
    - elasticsearch.json

- name: Adding Conf to enable dashboards
  copy:
    src: all.yml
    dest: /etc/grafana/provisioning/dashboards/
    owner: grafana
    group: grafana

- name: Adding Datasource to Prometheus
  template:
    src: all.yml.j2
    dest: /etc/grafana/provisioning/datasources/all.yml
    owner: grafana
    group: grafana
  notify:
    - start_grafana

