---
# tasks file for grafana
- name: Install Grafana on Debian
  include: debian.yml
  when:
    ansible_os_family == "Debian"

- name: Install Grafana on RedHat
  include: redhat.yml
  when:
    ansible_os_family == "RedHat"

