---
- name: Download and Install Grafana Package on RedHat
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - "{{ rpm_url }}"

- name: Move the configuration File of Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini

- name: Create grafana Dashboard directory
  file:
    path: /var/lib/grafana/dashboards
    state: directory
    owner: grafana
    group: grafana
    mode: 0755
  notify:
    - start_grafana
